In [28]:
import pandas as pd

df = pd.read_csv(r'C:\Users\Neil\Documents\VSC\Advanced Machine Learning\Gcash_Review_Clustering_Project\CCADMACL_PROJECT_COM222\Kmeans Clustering Results\Updated_2020\sentence_2020.csv')
# df = pd.read_csv(r'C:\Users\Neil\Documents\VSC\Advanced Machine Learning\Gcash_Review_Clustering_Project\CCADMACL_PROJECT_COM222\Kmeans Clustering Results\Updated_2023\sentence_2023.csv')
pd.set_option('display.max_colwidth', None)

In [29]:
df.head()
df['year'] = 2020

In [30]:
def sample_cluster(df, cluster_num, sample_size=15, random_state=41):
    """Filters reviews by cluster and review length, then samples a specified number of rows."""
    filtered_df = df[(df['cluster'] == cluster_num) & (df['review_text'].str.len() > 20)]
    return filtered_df.sample(min(len(filtered_df), sample_size), random_state=random_state)

In [31]:
Df_cluster0 = sample_cluster(df, 0)
Df_cluster0

,review_text,cluster,year
2793,"I tired to buy load in GCASH, GOSAKTO90, it only texted that 90 was paid but I didn't receive my load, I did it twice and now I lost 180 pesos in my Gcash acc and still no load, please do refund, I tried to check my load balance to my sim and if there's mobile data but it says I'm not registered to one.",0.0,2020
143,Great app easy and secure,0.0,2020
17998,PUTANG INA NYO PUTANG INA NYO HAYOP KAYO.BOBO KAYO. Update kayo ng update mga putang ina kayo.Tapos ayaw pa ang cash in sa lower version ng Android na supported nyo naman.Gago Kayo.Putang Ina Kayo.Magsara Na Kayo.P,0.0,2020
28068,Maganda po gamitin gcash,0.0,2020
23027,"i have n0ticed that y0u keep 0n updating alm0st every m0nth. & we have n0 0pti0n to decline it. otherwise, we will n0t be able to access our acc0unts. s0 hassle & very inc0nvenient! next update, surely will uninstall this app.",0.0,2020
8120,You simply cannot deliver what is expected and advertised. Poor customer support. Oh... i mean NO CUSTOMER SUPPORT AT ALL! This app is LOCKED too during ECQ. Failed! Uninstalling..,0.0,2020
17670,Galagut nako ha sige lang mo og update niya hinay hinay gihapon ang transtruction,0.0,2020
21518,"This app is really helpful specially in this time of pandemic.this app made this community home quarantine a lot easier.now,we can buy load,pay our bills and shop online anytime,anywhere!",0.0,2020
13678,Why I can't update d new version.. I can't open my account... Plsssssss.... Help me... I need it badly,0.0,2020
28230,You give me 15 load voucher. But i cannot use it. Your manloloko,0.0,2020
12708,"thank you so much ,gcash",0.0,2020
16144,"Worst experiences in this app so far. It keeps on deducting my money without asking me for a verification and such! I'm just receiving messages regarding the payment process and I don't know where did it came from. Also, they lack details regarding this issue. Worst service ever! If only I could give negative star 😡",0.0,2020
9744,Ang hirap kumita ng pera,0.0,2020
13419,puro update.. diyosko lord,0.0,2020
27369,"gcash has been always on the choices when it comes to paying something and having the app to have a support for students will be good! student's id isn't available, and last last last time, the cam quality isn't good. Please update it for the better spc bcs it's widely used now in the pandemic, and I'm willing to rate it higher next time.",0.0,2020

In [32]:
Df_cluster1 = sample_cluster(df, 1)
Df_cluster1

,review_text,cluster,year
14241,its great .. . AMAZING APPS...,1.0,2020
21178,"When I updated the app, it can no longer be use. What shall I do?",1.0,2020
19627,"Maganda ang app at madaling gamitin lalo na sa Mobile legend, pambili ng diamond. Sana po madali ang pag change number kasi nagtanong ako sa customer support, kung nagchange ka number kailangan gumawa ka ng bagong account with the same information sa ibang account",1.0,2020
2997,"Super convenient! Saves time, effort and resources by avoiding the queues.",1.0,2020
27885,"I used to love Gcash before, but now, I dont like the new update where theres a charge for convenience fee when you do bank transfer. But I guess I would just use my bank mobile app to do transfers, rather than using GCash.",1.0,2020
23084,i lost 1350 in may gcashmoney.. i dont know where it go..,1.0,2020
9895,Lagi nalang nag mamaintenance and lagi nag papa update 😔😔😔 anyare naba kaka update lang ng june 2 update nnaman,1.0,2020
25490,Convenient but sometimes error occur,1.0,2020
24164,good namam pero update ulet pleaseee.,1.0,2020
17461,Ang hirap mag log-in di agad nasesend ang OTP,1.0,2020
10221,"I give three stars because it doesn't want to confirm my email. Now I am using it just to save money or transfer my money to my bank account. And I can't use the other part of this app because it says ""you need to confirm your email first"" but it doesn't want it.",1.0,2020
10225,Touch ID/Fingerprint unlock would be a great addition.,1.0,2020
18060,Savings and loading apps is good not just for older one but also for the millennials.,1.0,2020
14208,tumbs up... my life getting easy,1.0,2020
3191,great.. i hope it last..,1.0,2020

In [33]:
Df_cluster2 = sample_cluster(df, 2)
Df_cluster2

,review_text,cluster,year
14730,Its so helpfull apps... The Gcash is..,2.0,2020
14988,Lagi nlang nag e error sa transaction ng load.......,2.0,2020
18320,Nice and convinient app. I hope for continuous excellent service,2.0,2020
1093,Very fast this apps i love it,2.0,2020
8237,"Several times the load would not reach to the number I load. Please fix this, it doesnt have where to complain either.",2.0,2020
28641,i going to change my profile pic and i already fully verified why you always me ask for i.d i already sent 2 i.d and i cant edit my profile pic. tss,2.0,2020
12816,Sometimes it's unavailable but its good app.,2.0,2020
4421,No reply for my authentication code. Damn it. Please fix it. I barely need to access my account,2.0,2020
13248,The best app i ever seen in my life its legit and good this app are so amazing❤️ plsss get back the student ID plss 🙏🙏🙏,2.0,2020
4872,"I have one problem with this app when I putting the PRN number when I attempt in paying SSS, the letters are not working only the number is working. The first two letters of system generated PRN is not working. Please fix this apps ASAP. Please fix the SSS PRN",2.0,2020
11079,Oh my god! The services was very good but how can I verify my account if your camere was too dark and blurry unlike my real camera. I hope to dix it....,2.0,2020
13527,why i cant open my app now. Updated app.. i need to send money,2.0,2020
6268,Hindi na pwede ma log in ang gcash. May internet naman ako at tama ang password.,2.0,2020
7630,Kapag ng invite dw using referral code mag eearn ka pero almost three weeks na since ginamit q referral ng asawa q. Wala nmn.,2.0,2020
14568,I enjoy using this app.. Thank you so much 😘,2.0,2020

In [34]:
Df_cluster3 = sample_cluster(df, 3)
Df_cluster3

,review_text,cluster,year
12437,I tried linking my payment to this account but after loading it always shows me a blank screen even though my internet is really good. I don't know if any of you like this app but it always gives me a bad day and a bad mood every time I use this app. So please fix this problem if you want a good ratings from your users.,3.0,2020
16520,I'm already trying to verify my account for like 7 days. It always say that the photo ID is unclear. Like what the--! How clear do you want? 😭 I want to start my business right away but I cannot because of this. 😭,3.0,2020
12280,"The app have so many bugs. It's been weeks and I havent been able to open a savings account, help center couldn't fix my problem.",3.0,2020
19621,Not really good the updated version,3.0,2020
15629,Email verification has issues. It doesn't send email.,3.0,2020
15589,Magandang apps po ito,3.0,2020
20650,"I couldn't register my other sim. The other one, after registering I don't receive authentication to switch on another device. Plus gcash texted me that I received my cashin but my balance remains 0. It sucks!",3.0,2020
8944,I CANT GET MY ACCOUNT TO BE VERIFIED BECAUSE THE SEE OTHER AVAILABLE ID DISAPPEREAD FOR MY STUDENT ID TO BE VERIFIED FIX THIS BUG,3.0,2020
10775,Bad app not using a vouchers,3.0,2020
12567,Very easy to use! I also appreciate the fact that I can use GCash as an alternative for Bank Deposits especially since this lockdown period. Thanks for making this app!,3.0,2020
24666,"Best financial app for me. So far, I only had minimal issues with my GCash experience since I started using it on March this year. Just a suggestion though: please notify us via SMS when you have a service maintenance because you guys seldom do that. It's a bit inconvenient to open the app just to be surprised that there's a maintenance. Otherwise, keep up the good work!",3.0,2020
27742,"This is such a bad app, i have been contacting their customer service and i haven't recieve any response yet. I made a transaction to transfer money from my bank account to gcash, i have been deducted in my bank account but it doesn't reflect in my gcash account. How many times do i have to contact you to give my money back? Such a scam. Just give my money back and i will surely delete this app. You truly deserve a rating lower than 0.",3.0,2020
16280,E-mail verification code is still very hard to receive. And why is my personal details different now though my picture is still me?,3.0,2020
26142,The biller profile saved lost its content after the update.,3.0,2020
26772,"Hard to get verified as a student. Paikot ikot lang kami ng ""Gcash Help Center"" paulit ulit ako ng send requirements, laging unable to process?? I've already tried 3 times, (4th attempt now).",3.0,2020

In [35]:
Df_cluster4 = sample_cluster(df, 4)
Df_cluster4

,review_text,cluster,year
28477,Verification process needs improvement!! I'm doing everything I can to take a picture of my ID but when I took the shot it gets blurred every single time! It sucks!!,4.0,2020
6114,Laging under maintenance pki ayos naman ang system nio,4.0,2020
364,Sometimes login prblem.. 🤔 but i love GCash.,4.0,2020
13934,Easy access for bills payment bank deposits etc.(cashless),4.0,2020
16663,So many glitches and errors! It says my transaction limit has exceeded even when it has not. They don't have an estimated time frame as to when they'll be able to fix the issue. Nakakapagod.,4.0,2020
22744,May charge sa bank transfer 😢,4.0,2020
12378,Thankfully for us many more come my life thanks piso. Will i come again..,4.0,2020
14671,Like it and love it makes my life more easier!,4.0,2020
7470,Hello Gcash I am ur user for a few years now but I stopped using it and now i continued so I reffered to a friend but its been a week but no money has been recieved and weird thing is when I looked in the reffered friends I reffered 3 friends before and had 150 but As I said I reffered to a new friend but the counter said I reffered to 4 FRIENDS BUT thr money is still 150...It should be 200 right??,4.0,2020
21979,"I can't login to my account it always says ""something went wrong"" I don not like it. I kept repating it but it always says ""something went wrong "" I already go to the ""help center"" but It didn't help me at all.",4.0,2020
22927,Verry easy and convince,4.0,2020
13076,i hope it can add other valid id's like tin id since some who uses the app are students and not all have the updated required id's. i really can't transact my transactions since the id required is hard for me being a student.,4.0,2020
29035,"easy to use especially on sending money anytime , anywhere.",4.0,2020
18631,Puro update ng update ng wala nmn pagbabago nakakainis na laging wrong timing,4.0,2020
26455,Hmmm ok unta pero sige ug update.. I hope this will maximize soon . Makahurot nmu ug space,4.0,2020

In [36]:
Df_cluster5 = sample_cluster(df, 5)
Df_cluster5

Empty DataFrame
Columns: [review_text, cluster, year]
Index: []