In [34]:
import pandas as pd

df = pd.read_csv('dbscan_sentence_2023.csv')
# df = pd.read_csv(r'C:\Users\Neil\Documents\VSC\Advanced Machine Learning\Gcash_Review_Clustering_Project\CCADMACL_PROJECT_COM222\Kmeans Clustering Results\Updated_2023\sentence_2023.csv')
pd.set_option('display.max_colwidth', None)

In [35]:
df.head()
df['cluster'] = df['dbscan_cluster']
df.drop(columns=['dbscan_cluster'], inplace=True)
df['year'] = 2023

In [36]:
df

,review_text,cluster,year
0,"When I open my g-cash, I got to choose later & try again then G-cash icon automatically disappearing in my phone after choosing later so I un-installed and download g-cash again. Fix your g-cash apps.",0,2023
1,Stupid app i used my original psa but they told me that my verification is unsuccessful not real? what the heck!,1,2023
2,app keeps disappearing,0,2023
3,Good but I can't dl it anymore why?,2,2023
4,Lage nawawala sa cp ko di ko.alam kung bakit.,3,2023
...,...,...,...
70177,"Tang ina nyo pinapahirapan nyo mga gumagamit, dami nyo alam! Kukunek ka nka wifi na nga ssbhin mag data, nka data na switch to wifi dw pakyu kau",0,2023
70178,Scam n ngaun ang gcash n yan,0,2023
70179,Ayusin nyo otp nyo bulok masyado. Ang tagal dumating. Need na need na ng pera pang gamit nakakaabala na kayo sa tao .,3,2023
70180,Walang kwenta wag nyo na to i download,0,2023
70181,"Wtffdd, what happen, it constantly force to close the app, my device is not secure ??, wtff, is the developer of this application really do they job ??, if they then why it constantly close 🤬",0,2023

In [37]:
def sample_cluster(df, cluster_num, sample_size=15, random_state=41):
    """Filters reviews by cluster and review length, then samples a specified number of rows."""
    filtered_df = df[(df['cluster'] == cluster_num) & (df['review_text'].str.len() > 20)]
    return filtered_df.sample(min(len(filtered_df), sample_size), random_state=random_state)

In [38]:
Df_cluster0 = sample_cluster(df, 0)
Df_cluster0

,review_text,cluster,year
42113,"Huge banner ads in the app. That's just disgusting. There are 4 kinds of ""send"", padala, and transfer. Why not put remit, transmit, pay, convey, wire, and dispatch as well? Para mas magulo. Always some useless message when opening, making payments a slower process. Always ""something went wrong"" when opening. Edit 7/17/23: ""something went wrong"" every friggin' time I open the app. Now, it just won't open. PH fintech at its finest. Keep this up, and Maya will take over.",0,2023
51921,"okay para sa akin,malaking tulong mabilis Ang proseso",0,2023
34091,Kaso bkit lagi update ka sora,0,2023
15651,Dati good kasi convenient at walang madaming kaltas ngayon para nang bombay kada transaction may tubo kaltas ng kaltas specially sa load hays sana ibalik yung dati na free transaction.,0,2023
19052,Can't log in even after update,0,2023
45264,Very easy and rial able,0,2023
26801,No action for cancel transaction i lost lot money for q mistake number,0,2023
39252,"Easy to use with limited transactions in buying prepaid load. I like Gcash specially in paying bills ... SINCE YESTERDAY, july 27, 2023, I found it VERY HARD to use Gcash to pay for my purchases after answering your long questioner. Now I CAN NOT open my Gcash with still about Php 5,000. GIGI can't resolve. I want a live IT Professional to answer my problem. Thanks.",0,2023
46120,What the f gcash makaka send ng money pero di natatanggap ng na sendan ang galing na bawasan ang balance pero di na recieve ayusin nyo serbisyo nyo,0,2023
69710,"I hate this app. Such an inconvenience. Doing things on the go and repeatedly being told ""your device is not secure."" it's just so frustrating",0,2023
51216,tanginanyo nagloloko apps nyo,0,2023
22168,PUTANG INA MO GCASH KA,0,2023
11808,good app.. we can save money for this apps..,0,2023
5417,"Just in case you dont have enough data balance sometimes this app, requires you to update the app not knowing you dont have enough balance. You cant use this app without update. So hassle.",0,2023
46621,"Whenever I enter my Gcash mpin I can't log in ""something went wrong"" always pop up. I tried all the ways and steps about trouble shooting shown in the app but still it doesn't work. Please find a solution about this.",0,2023

In [39]:
Df_cluster1 = sample_cluster(df, 1)
Df_cluster1

,review_text,cluster,year
3234,stup1d app when i verifying my account when i take picture on front it says okay! But when taking picture at the back it says unclear even dfqing photo i took is clear,1,2023
68336,Experiencing piracy on gcash,1,2023
19566,I cant open it after the facial verification it wont let me in do i look like im not the owner? I know your strict with your security but can you except the ignorants of others for infact code is just fine if I care with my money Ofcourse I will not share it fix your system.,1,2023
62957,Always update! update! update! I can't even use it when im on emergency!,1,2023
26148,"About the update, is it necessary to update every month sa gcash app? Kumakain lang lalo ng phone storage etong app na ito, ano paba ang dinagdag?",1,2023
37099,"Can't open and change my MPN cause I forgot everything especially the questionnaires which is part of the security. So, please help me recover my account GCASH.",1,2023
25051,Putang ina mo gcash 5700 laman gcash ko bat ayaw mabuksan kahapon pa need ko pera yawa ka,1,2023
1780,Worst app. All transaction is not safe!,1,2023
4443,updating of new version is too slow,1,2023
5186,Why the gcash always update when it comes i need to use it .,1,2023
45597,Can't process a load.,1,2023
30963,This app is so good I've been trying to install other apps but it's not good quality but one day I found gcash,1,2023
45672,I can't recover my verified old account same name,1,2023
46363,Missing gcash in my app drawer. It's so inconvenient to uninstall and install the app again and again,1,2023
31549,i tried several times to verify my account for a 2 consecutive days using my national id but it keep saying it's blurr,1,2023

In [40]:
Df_cluster2 = sample_cluster(df, 2)
Df_cluster2

,review_text,cluster,year
5222,Walang kwenta pag nagkamali ka ng send ng Pera di mo rin pala mabawi.,2,2023
51334,I GONNA RATE IT 3 NOW CAUSE OF MAINTENANCE,2,2023
11856,This is the second time the nag claim ako ng remittance from MoneyGram direct to Gcash na nag error system nyo at yung pera di nag show sa account ko at 48 years bago nyo ipasok yung pera sa account ko!!!! Nag show naman na sa system nyo pero pahirapan kelangan pa kulit kulitin kayo para ipasok nyo yung pera sa account ko!!!! Nakakapeste!!!!,2,2023
34991,"App is getting slower and slower. Linked bank account often gets unlinked. And the fingerprint auth isn't working anymore, I always have to use my mpin.",2,2023
49323,I cant open the app. Not working,2,2023
58655,Thare a bugs of your apps,2,2023
39288,Why gcash can't update. I tried many time and it's error...,2,2023
8113,Been using this apps for a years and it is very helpful for easy transactions when it comes to money transfer and payments.,2,2023
47757,"You gave us maintenance schedule but you didn't fulfill your announcements we expect that date and scheduled payments after the maintenance or what you say ""fixes"" and what do you people want us to do? Damn! fix your schedules and app please!",2,2023
12816,"It's been 9 days and nothing has happened, the details are always being taken but no one is taking care of my concern, it's hard to talk to you, my account needs to be verified so that my money can be transferred to my new account, you keep repeating it saying, how long will I have to wait?",2,2023
55331,Cannot access the app since October started I already uninstall it and install again but there is progress. It is frustrating!!!,2,2023
26497,"update ng update, wala naman nangyayari. nakakabwisit",2,2023
58993,Hnd maopen agad. Need pa reinstall para ma open.,2,2023
26820,"Your gcash double safe is such a hassle. I wasn't able to get my allowance because I can't open my Gcash!! BRING BACK THE OLD GCASH WITH NO FACE VERIFICATION! Just please bringe back my money, it's my school allowance.",2,2023
64116,2 stars Laging nag uupdate .ano to weekly update??,2,2023

In [41]:
Df_cluster3 = sample_cluster(df, 3)
Df_cluster3

,review_text,cluster,year
9023,Struggling everytime i open the app always asking error/update Inconvenience!🙂,3,2023
16837,"Thank you. I appreciate the developers, support team, and all the staff and owners with their patience, goodness, peace, joy, and love to the people..",3,2023
60879,"Can't even buy a Game because ""OoPs InVaLiD, Qr CoDe""",3,2023
52075,Maganda ang gcash kasi nakakaloan and nakakaipon pero as of now 3 out 5 dahil yung pera na nasa gcash ko ay nabawasa ng 300+ which is malaki na sakin kasi I'm a working student. Hopefully na maibalik sakin yung 300+ or else I'll report it. Thank you,3,2023
52152,"why would you add a stupid function that auto closes the app when ""the developer"" option is on??????? i cant turn it on/off whenever i have to open a single app cause it resets the settings that i changed in the developer options... fix this please!!!!!",3,2023
40801,It keeps on disappearing on my homescreen. I had to uninstall and reinstall it again. Same issue.,3,2023
17430,I can't download or update,3,2023
3182,"Not good .. untrustworthy .. how many times does a scammer get my money via their platform however they did not put any actions ..im so disappointed to trust these platform, because aside from scammer that can easily get in to your account there is a notification as well that you owe money . I WONT RECOMEND THIS PLATFORM TO ANYBODY BECAUSE YOUR MONEY IS NOT SECURE",3,2023
6684,Laging nawala gcash ko,3,2023
43248,"The additional charge in buying load here was too expensive, 2% is big amount esp for poor pilipino people",3,2023
25047,Always something wrong whats happening i cant get my money because the app cannot open.,3,2023
43021,Puro update kada bukas,3,2023
19839,PLEASE pakibalik mga pera ng mga tao!,3,2023
6896,sana maayos na ung gcash nio,3,2023
48717,So very easy to use it and no kind of problem for our daily using us,3,2023

In [42]:
Df_cluster4 = sample_cluster(df, 4)
Df_cluster4

,review_text,cluster,year
64195,Only 1 star because they didn't accept my verification I verify my account 3 times but still nothing,4,2023
15517,utility bills the font was so so so big cant read my account number if correct this app now is trash need to 0 star for this and find for replacement for gcash app!!!!,4,2023
42752,"So hard to get verified, fix the scanner",4,2023
5,Yes its nice this app,4,2023
17070,sana po maopen ang gcash ko kahit walang load kilangan kopa po magpaload para maboksan gcash ko dapat d2 sana aq magload sa gcash q sana po pwdi salamat po,4,2023
49163,**Pros: Convenient. Only use this for paying. **Cons: 1)Ads AT EVERY LOGIN and payment/transfer confirmation. 2)Getting sluggish as more and more features gets jammed in the app. 3)Randomly logs me out when there's an update and have to go through tutorial again while in front of a queue at the cashier. 4)Fees to be added soon. 5)Unneccessary developer options blocking feature. Lazy developers being lazy.,4,2023
45346,Ang hirap mag login sa app na to sobrang hassle laging error after mo ilagay pin or biometric. ERROR CONNECTION lagi eh okay naman internet ko.,4,2023
35892,taman aman pinapasang ID decline ng decline,4,2023
68494,Hello My dear Gcash! Can you please help me to log in😰 Ived done all the suggestion on Gigi chat. Everything it says there nagawa ko na. Many times. Every 30min/hour. But still can't log in. There is one thing only I can't do. To send the ticket ID your asking😰The question is where I can't find that ticket number. I try many time the suggestion in Gigi's chating. But there is no ticket number seen there😰 Can you please let me open my gcash🙏🙏🙏,4,2023
70175,Always consistent having several issues and irregularity problems please try to fix asap,4,2023
9172,Every time i use ang bagal mag log in,4,2023
55010,Why this app is always updating? Like many times a month. Annoying,4,2023
53912,How to open my Gcash application update,4,2023
68008,I used your app for a long time but this update make my day so bad i encountered your security issues and it was so useless i cant use the app fix this please !!!!,4,2023
30485,National ID gamit ko pero ayaw tanggapin bulok,4,2023

In [43]:
Df_cluster5 = sample_cluster(df, 5)
Df_cluster5

,review_text,cluster,year
39167,"Whenever i didnt use the app recently, once you log in again. Needed to do update, i already update the app but hence needed to update again🙈",5,2023
36986,Newest update isnot helping pls fix the problem iLike it just the way it is in working mode,5,2023
14447,good for savings ez to pay,5,2023
18436,"taenang gcash to! araw-araw update? kung kailan naman ako nagmamadali saka maupdate ampota. Ang tagal din magverify, sabi isang linggo lang potaena yan isang buwan na baga. Isa lang masasabi ko, BWCT!!",5,2023
17288,"Scam prizes, cannot be used if the voucher is for glife only.",5,2023
30451,"Maraming kawatan na nagbebreach sa security system ng app. Matagal pa magrespond sa concerns ng mga customers, imbes na itake nila as responsibility yung mga nawawalang pera they would ask you to report it first sa police tas wala man lang gagawin. People trusted you with their money, pero simpleng update sa security nyo di nyo pa magawa? Andami nang biktima ng send money transactions na WALANG OTP NA SINESEND and isa nako ron. DI PORKET NIRISK NG MGA TAO YUNG PERA NILA SA INYO PABABAYAAN NYO.",5,2023
24448,Napka wlang kwentang apps,5,2023
14034,Same as the problem form others not verified! And its already a month of waiting 😏,5,2023
12526,I reinstall the app 3 days past still i cannot buy load,5,2023
18955,Saan koba makikita ang shutang inang ticket number yan ..gcash daming mong alam,5,2023
10452,Does not load when launched,5,2023
22658,Okay G ulit later Uninstall na kita... Sa paymaya nlng ako.,5,2023
22956,Putaena araw araw nalang maintainance 😡😡,5,2023
28275,Yaway aritao nueva vizcaya,5,2023
12188,Dapat wala na ang face recognition sagabal lang yan tama naman ang pin ehh tapos need pa nang face recognition 🤔,5,2023

In [44]:
Df_cluster5 = sample_cluster(df, 6)
Df_cluster5

,review_text,cluster,year
50541,Kaumay... mula ng nag update ndi na mai open. need pa i close ang developer options. ndi naman ganito dati. kaumay.,6,2023
39365,It always have an error and for updates sad to say its useful 😔,6,2023
52560,What is this security of unknown sources?!!? i am unable to open the app. unknown sources s disabled!,6,2023
69542,I keep on geeting stuck. The OTP sent to me would never work. I can't get back to my dashboard. Please help me on my issue.,6,2023
29963,I cannot login always says that submit a ticket,6,2023
49527,"The app is getting worse when it comes to usage. Every time I'm gonna do a transaction, it closes without a reason, like why!? They always do maintenance, yet they can't even make it a user-friendly experience. So Disappointing!",6,2023
48337,"super good, and very useful ❤️",6,2023
35772,Its so usefull and fun to use because this have games that you can play,6,2023
30121,Bakt ayaw mag install ng gcash importante kase to,6,2023
56778,"Hindi mabuksan kaumay, may pera ako don at need ko tapos ganito",6,2023
30418,YUNG FACIAL RECOGNITION BULOK,6,2023
33497,Five (5) star talaga ang gcash eh... Malaking tulong....thank you so much gcash,6,2023
18065,"Bulok service niyo Hindi man lang gumana,Wala man lang working system eh nakailang ulit na ako mag submit a ticket sa Inyo Wala pading working!",6,2023
6445,Bulok wa it pueos di maka register,6,2023
4984,It's not easy to go on esp if I need to load .as of now I want to load extra99 but I can not get through. I knowb i have still money on my gcash.thanks,6,2023

In [45]:
Df_cluster5 = sample_cluster(df, 7)
Df_cluster5

,review_text,cluster,year
46398,Matagal mag download pero kailangan pagtyagaan.,7,2023
62601,I cant log in it says submit a ticket,7,2023
27534,way boot....nangatug guro ni sila..dugay kaau veryfy,7,2023
5636,I can't use my gcash because it says something is error. Please fix it for the troubleshooting.,7,2023
31843,Can we pls request to ask union bank cash-in notifications to put the OTP at the front of the SMS message so when it pops up i'll be able to see it immediately,7,2023
50793,Something problem with this apps somte times I can't log in always the problem is internal server ...I make it to reinstall and uninstall and cache all mb but all the same...very hassle I can't pay online shop because of this trouble,7,2023
25795,Not good not working if no load 1 star,7,2023
39406,"I try to reset my pin but sending code in email does not help because it's too long to received, after I received the code and enter the code it will said the its already expire. Please fix it. I can't reset my pin because of the code is too long to send in my email.",7,2023
32526,"its always ""something went wrong"" and i cant recover my MPIN please take action for this problems!!",7,2023
60617,Always something went wrong my g cash app not working what hqppend,7,2023
58664,Install again and then i Uninstall again coz after open the apps itself.. the problem is i can't click and the keyboard didn't appear (in short there's a problem in log in using my globe phone number.. so disappointed...) So i decide to use this apps on my Ipad instead of my phone. Can you fix the apps so i can install this app on my phone again.,7,2023
29648,Bad experience I paid some promo vouchers but I can't use it because the system maintenance and always saying try again.,7,2023
63696,Technical problems most of the time,7,2023
68116,kng hihingi mn kayo ng refund wag na kayong mag aksaya ng oras. yng customer service nila napakapangit. maliit na concern hindi pa rin ma resolve hangang ngayon.,7,2023
56255,"The new ban interacrion sucks, its so sudden, like what do you expect us to do? get a new phone just like that? I dont even have my phone rooted and it keeps showing me the warning and does not let me use gcash anymore.",7,2023

In [46]:
Df_cluster5 = sample_cluster(df, 8)
Df_cluster5

,review_text,cluster,year
15059,I cannot proceed my online payment transaction😌,8,2023
54920,i cant log in the app shows that my device is not safe ?? what the ... i've been using this phone for almost 3years and this phone is safe and also using this app for almost 2years but now what happen,8,2023
16479,Sana yong tin I'd maging okay khit Di pupunta sa remittance,8,2023
32130,Why i cant ricognize my face in gcash application,8,2023
12651,I can't say enough. This apps is really good,8,2023
16498,there's so many security dude I need to open my gcash account because my mother sent me money and the gcash need face verification? how can I open this now,8,2023
183,Bulok scanner niyo sa id nag papa verified ako hindi gunagana ayosin niyo serbesyo niyo sa inyo pa naman pinag kakatiwala pera namin sa inyo hayst 😤,8,2023
50499,"My money in this app suddenly dissapeared and there's no such transactions recorded about sending money with the amount lessend in my account, why is it?",8,2023
54760,What happened gcash. Cnt open it ... Please fix ths ive been using ths app for almost 3 years very usefull fast and easy transaction 5 stars for you x,8,2023
12277,Super helpful talaga.. thank you so much 🥰🙏,8,2023
38790,You keep on forcing us to update the app. Until we can no longer have access on to link our mobile banks. It so frustrating!,8,2023
61426,Dili ma open tas pag e lick ko e may naka lagay na something worng ano ba to🤦,8,2023
34726,"pangit ng update niyo palagi, mag uupdate tapos paulit ulit ayusin niyo naman update niyo",8,2023
64865,"Ano na gcash, paki ayos naman oh",8,2023
45594,"if i can give 0 stars, i would. bring back the text messages. this is so pro scam",8,2023

In [47]:
Df_cluster5 = sample_cluster(df, 9)
Df_cluster5

,review_text,cluster,year
47072,Sms notif on transactions in ginvest are late. Very late.,9,2023
33912,"So far so good. My concern is who will be responsible for the account in case of lost of phone, in order to retrieve the money in the gcash account.",9,2023
16408,"the app is running nicely but in terms of security its pretty bad, my phone was stolen alongside its registered sim, i contacted gigi which was so slow because of the typing animations it had, and submitted like 4 tickets, i managed to get the stolen acc suspended but weeks after i think they lifted the suspension of the account probably because they had access to the stolen sim, and i submitted an account deletion form but got no news. now in the present i think they are still using my account",9,2023
43990,Kinginang update yan pa downgrade.,9,2023
58897,It is installed but I cant find it anywhere. What's wrong gcash?! This problem needs to be fixed,9,2023
30077,Not the app but the service itself. I used GlobeOne to purchase load but I can't receive any OTP. Tried 6 times already with 5 mins waiting time each. Chat assistant is useless.,9,2023
45731,"I rate the apps 1 star, because my account still not verified after 2year ago..",9,2023
6368,Giving this a 1 simply because of the pop up when you open the app. This is the only app I have that does this and 99.99% of the time I would misclick it and have to ancitipate it before doing anything because I want to head into bills payment quickly.,9,2023
21189,Useless! Customer support does not provide you with any updates regarding the ticket that you have submitted.,9,2023
3566,So far im satisfied with the features .. I have been using this apps for morethan 2yrs now. And my gcredit already increase :),9,2023
35762,Unreliable piece of shii. Switching to maya,9,2023
9241,It's convenient when it comes to transfer money and payment transactions however what I didn't like about this app is it always ask to update (most of the time) the app.,9,2023
50938,Why account suddenly close,9,2023
44821,App suddenly disappears,9,2023
47448,Sana pwde na ako makaloan need ko na😭😭,9,2023

In [48]:
Df_cluster5 = sample_cluster(df, 10)
Df_cluster5

,review_text,cluster,year
18191,Very fast to claim the money,10,2023
18904,TANGINAMOOOOOOOO DI AKO MAKAPAG VERIFY,10,2023
11615,"why does it always need annoying update but still can't function well, laging lag , even logging in always may issue, verified user ako pero laging nagkaka problema sa log in.",10,2023
48391,"Hii gcash, bruh when Im trying to login in my account it keeps saying ""something went wrong please send a ticket for further assistance"" I already send a ticket and I been waiting for it to be fixed for 2 years pls help.",10,2023
61728,"I updated the app last week but after the update, i can't send money and pay bills because of the message that the device i'm using is not secure. I re installed but until now i still can't use it. Please fix this.",10,2023
34857,"Shortcut icon is always removed every update. And now I cant see the app, needed to re install before I can use again.",10,2023
18839,"I put a correct MPIN but it keeps saying it's wrong,this aps give me headache",10,2023
53722,Nwwla ang gcsh app q. I can't open my gcash.. Nag install aq ulit.. But still I can't open..sayang laman ng gcash q..,10,2023
13436,Need always update ayts,10,2023
57723,Nawalan ako pera ngayon ayaw naman bumukas,10,2023
32598,"nakagamit ako ng gloan twice, nakakapag taka bakit ayaw gumana ngayon di ko nalang muna sana binayaran 🤬🤬🤬🤬",10,2023
46635,"I used to like this app because whenever someone will send money to me. Gcash will send a message as well or rather it will notify me. But now, since it updated i no longer know if someone is sending message because it's not giving notification! You will only know someone is sending if u will open the app! Why??????",10,2023
49681,"Can't open it ,unless i turn off my dev. Option",10,2023
25243,Wag na mag install nto bulok bigla ayaw bumukas trouble shoot daw tpos pag nag submit ticket ka wala din d n marecover,10,2023
16308,Cant open my acc. until now bc of the update 3rd Update: I cant use my gcash,10,2023

In [49]:
Df_cluster5 = sample_cluster(df, 11)
Df_cluster5

,review_text,cluster,year
19275,Gcash ko 1week na hindi maopen nakailan submit ticket ako wala parin nangyayare. May laman pa nman gcash ko at sana maaksyunan ninyo ganto issues.,11,2023
32842,"Can't login since yesterday, , it keeps on loading and loading",11,2023
20658,don't use this it's not safe,11,2023
24447,I can't do my acc in gcash,11,2023
56628,Always keep updating and sometimes there is problem in opening,11,2023
22627,anu na gcash di ko na ma open yung app baka ma thank you na yung pera,11,2023
67175,the icon keeps disappearing in my home screen and app drawer,11,2023
49056,bakit di pa ko ako nakareceive nang 6 digit OTP..2days now i cant open and access my gcash...please need some actions about this..,11,2023
21448,Very nice game i have done many wins than losses i wish i have a money hewards on g cash how can i claim. I dont have money if the game is charged in me the game commando strike!,11,2023
47196,"Thanks so much for GCash app! (GCash Visa card, GCrypto) I don't use hucking banks at all! This is the best app it the world! GCash one love! ❤️",11,2023
19493,"The latest version of gcash ap is not ompatible with my SM-A725F/DS with upgtaded to andriod version 13, ONE UI 5.1",11,2023
11228,"The latest update is so annoying, why do we need face selfie in the first place and now and I can't open my gcash it because face selfie i got many error",11,2023
28339,Laging something went wrong. Ano un? Ano ba namang klaseng service ito.,11,2023
23674,I connot accesss anymore my gcash account,11,2023
48273,as of now ok naman po gamitin no hassle sa pagbayad. may error minsan need to click help daw submit ticket then pag submit naman ng ticket code wrong naman kahit 3x ko na input.,11,2023